[phases.setup]
aptPkgs = ["libpq-dev", "gcc", "libjpeg-dev", "zlib1g-dev", "curl"]
nixPkgs = ["rust", "cargo"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
